shiro:
  loginUrl: /login
  unauthorizedUrl: /unauthorized

  aad:
    tenant:
    tenant-id:
    client-id:
    post-logout-uri: /lobby
    redirect-uri: /login
    filter-chain-defs:
      "[/static/**]": anon
